// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using TransNet.Persistence;

#nullable disable

namespace TransNet.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260815000000_AddClientLocation")]
    partial class AddClientLocation
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
