namespace TransNet.Persistence.SeedData;

internal sealed record InventoryPartSeedRow(
    string? PurchasedAt,
    string Supplier,
    string Item,
    string Specification,
    decimal? Quantity,
    decimal? UnitPrice,
    decimal? TotalPrice,
    decimal? AmountInPeso,
    string ProjectBuilding,
    string LineKind,
    int SortOrder);

internal static class InventoryPartSeedRows
{
    public static IReadOnlyList<InventoryPartSeedRow> All { get; } = new InventoryPartSeedRow[]
    {
        new(
            "2025-01-21",
            "XI'AN OAN LIFT PARTS CO., LTD.",
            "TCB-3 Board",
            "",
            1m,
            380m,
            380m,
            null,
            "",
            "Part",
            1),
        new(
            "2025-01-21",
            "XI'AN OAN LIFT PARTS CO., LTD.",
            "Display Board",
            "",
            2m,
            35m,
            70m,
            null,
            "",
            "Part",
            2),
        new(
            "2025-01-21",
            "XI'AN OAN LIFT PARTS CO., LTD.",
            "Freight By Air",
            "",
            null,
            70m,
            70m,
            null,
            "",
            "Charge",
            3),
        new(
            "2025-01-21",
            "SUZHOU PROFESSION ELEVATOR CO., LTD.",
            "Monarch Controller Inverter",
            "Monarch system inverter with PG card and main board",
            1m,
            525m,
            525m,
            null,
            "",
            "Part",
            4),
        new(
            "2025-03-01",
            "SUZHOU PROFESSION ELEVATOR CO., LTD.",
            "Buttons",
            "",
            4m,
            2.5m,
            10m,
            null,
            "",
            "Part",
            5),
        new(
            "2025-03-01",
            "SUZHOU PROFESSION ELEVATOR CO., LTD.",
            "Car Fan",
            "",
            1m,
            30m,
            30m,
            null,
            "",
            "Part",
            6),
        new(
            "2025-04-21",
            "SUZHOU PROFESSION ELEVATOR CO., LTD.",
            "Door Shoe",
            "",
            null,
            null,
            null,
            null,
            "",
            "Part",
            7),
        new(
            "2025-04-21",
            "SUZHOU PROFESSION ELEVATOR CO., LTD.",
            "Button - replacement",
            "",
            null,
            null,
            null,
            null,
            "",
            "Part",
            8),
        new(
            "2025-05-09",
            "SUZHOU PROFESSION ELEVATOR CO., LTD.",
            "Safety Circuit Board for Escalator",
            "",
            1m,
            null,
            150m,
            null,
            "",
            "Part",
            9),
        new(
            "2025-06-16",
            "FUJI ELEVATOR INDUSTRY CO., LTD.",
            "DELTA Inverter",
            "Model : VFD022M23B",
            1m,
            495m,
            495m,
            null,
            "",
            "Part",
            10),
        new(
            "2025-06-16",
            "FUJI ELEVATOR INDUSTRY CO., LTD.",
            "Banking charge",
            "",
            null,
            30m,
            525m,
            null,
            "",
            "Charge",
            11),
        new(
            "2025-06-16",
            "FUJI ELEVATOR INDUSTRY CO., LTD.",
            "Unionbank Cable charge",
            "",
            null,
            40m,
            40m,
            null,
            "",
            "Charge",
            12),
        new(
            "2025-07-21",
            "SUSHOU PROFESSION ELEVATOR CO., LTD.",
            "Door Motor",
            "",
            1m,
            180m,
            740m,
            null,
            "",
            "Part",
            13),
        new(
            "2025-07-21",
            "SUSHOU PROFESSION ELEVATOR CO., LTD.",
            "Home Lift Inverter",
            "",
            1m,
            520m,
            520m,
            null,
            "",
            "Part",
            14),
        new(
            "2025-07-21",
            "SUSHOU PROFESSION ELEVATOR CO., LTD.",
            "Unionbank Cable Charge",
            "",
            null,
            40m,
            null,
            null,
            "",
            "Charge",
            15),
        new(
            "2025-08-07",
            "SUSHOU PROFESSION ELEVATOR CO., LTD.",
            "Step Chains",
            "Fujizy escalator, 39 steps*6 joints",
            1m,
            795.4m,
            895.4m,
            null,
            "",
            "Part",
            16),
        new(
            "2025-08-07",
            "SUSHOU PROFESSION ELEVATOR CO., LTD.",
            "Ocean Fee",
            "",
            null,
            100m,
            null,
            null,
            "",
            "Charge",
            17),
        new(
            "2025-08-07",
            "SUSHOU PROFESSION ELEVATOR CO., LTD.",
            "Door Motor",
            "",
            null,
            null,
            null,
            null,
            "",
            "Part",
            18),
        new(
            "2025-08-07",
            "SUSHOU PROFESSION ELEVATOR CO., LTD.",
            "Elevator Fan",
            "",
            null,
            null,
            null,
            null,
            "",
            "Part",
            19),
        new(
            "2025-08-03",
            "SYMAX LIFT (CHINA) CO., LTD.",
            "Lift Pully",
            "",
            1m,
            59m,
            59m,
            null,
            "",
            "Part",
            20),
        new(
            "2025-08-03",
            "SYMAX LIFT (CHINA) CO., LTD.",
            "Door Motor",
            "",
            2m,
            80m,
            160m,
            null,
            "",
            "Part",
            21),
        new(
            "2025-08-03",
            "SYMAX LIFT (CHINA) CO., LTD.",
            "Proximity Switch",
            "",
            8m,
            5m,
            40m,
            null,
            "",
            "Part",
            22),
        new(
            "2025-08-03",
            "SYMAX LIFT (CHINA) CO., LTD.",
            "LOP Board",
            "",
            2m,
            10m,
            20m,
            null,
            "",
            "Part",
            23),
        new(
            "2025-08-03",
            "SYMAX LIFT (CHINA) CO., LTD.",
            "Catalog USB",
            "",
            1m,
            1m,
            1m,
            null,
            "",
            "Part",
            24),
        new(
            "2025-08-04",
            "SYMAX LIFT (CHINA) CO., LTD.",
            "Guide Shoe",
            "",
            4m,
            null,
            null,
            null,
            "",
            "Part",
            25),
        new(
            "2025-09-01",
            "XI'AN OAN LIFT PARTS CO., LTD.",
            "Guide Shoe",
            "16mm",
            8m,
            2m,
            16m,
            null,
            "",
            "Part",
            26),
        new(
            "2025-09-01",
            "XI'AN OAN LIFT PARTS CO., LTD.",
            "Guide Shoe",
            "8mm",
            8m,
            2m,
            16m,
            null,
            "",
            "Part",
            27),
        new(
            "2025-09-01",
            "XI'AN OAN LIFT PARTS CO., LTD.",
            "Polyurethane Buffer",
            "LD-HC-L2",
            4m,
            10m,
            40m,
            null,
            "",
            "Part",
            28),
        new(
            "2025-09-01",
            "XI'AN OAN LIFT PARTS CO., LTD.",
            "Cross Flow Fan",
            "FB-9B, 220V",
            2m,
            13m,
            26m,
            null,
            "",
            "Part",
            29),
        new(
            "2025-09-01",
            "XI'AN OAN LIFT PARTS CO., LTD.",
            "Load Cell Indicator",
            "",
            1m,
            50m,
            50m,
            null,
            "",
            "Part",
            30),
        new(
            "2025-09-01",
            "XI'AN OAN LIFT PARTS CO., LTD.",
            "Load Sensor",
            "",
            1m,
            20m,
            20m,
            null,
            "",
            "Part",
            31),
        new(
            "2025-09-01",
            "XI'AN OAN LIFT PARTS CO., LTD.",
            "Escalator Auto Lubricating System",
            "20108-III",
            1m,
            110m,
            110m,
            null,
            "",
            "Part",
            32),
        new(
            "2025-09-01",
            "XI'AN OAN LIFT PARTS CO., LTD.",
            "Intercom",
            "",
            2m,
            60m,
            120m,
            null,
            "",
            "Part",
            33),
        new(
            "2025-09-01",
            "XI'AN OAN LIFT PARTS CO., LTD.",
            "ARD without battery",
            "3 phase 220 11kw",
            2m,
            260m,
            520m,
            null,
            "",
            "Part",
            34),
        new(
            "2025-09-03",
            "SUSHOU PROFESSION ELEVATOR CO., LTD.",
            "Elevator Fan",
            "FB-9B",
            10m,
            45m,
            450m,
            null,
            "",
            "Part",
            35),
        new(
            "2025-09-03",
            "SUSHOU PROFESSION ELEVATOR CO., LTD.",
            "CW Guide Shoes",
            "16mm",
            28m,
            2m,
            56m,
            null,
            "",
            "Part",
            36),
        new(
            "2025-09-03",
            "SUSHOU PROFESSION ELEVATOR CO., LTD.",
            "Voltage Monitoring Device",
            "",
            1m,
            40m,
            40m,
            null,
            "",
            "Part",
            37),
        new(
            "2025-09-03",
            "SUSHOU PROFESSION ELEVATOR CO., LTD.",
            "Chain block",
            "2 tons, 9 meters",
            2m,
            60m,
            120m,
            null,
            "",
            "Part",
            38),
        new(
            "2025-10-29",
            "XI'AN OAN LIFT PARTS CO., LTD.",
            "Push Button",
            "",
            10m,
            3m,
            30m,
            null,
            "",
            "Part",
            39),
        new(
            "2025-10-29",
            "XI'AN OAN LIFT PARTS CO., LTD.",
            "IC Card controller device",
            "",
            1m,
            280m,
            280m,
            null,
            "",
            "Part",
            40),
        new(
            "2025-10-29",
            "SUSHOU PROFESSION ELEVATOR CO., LTD.",
            "Control Cabinet SMR with PG Card & operator",
            "",
            1m,
            4060m,
            4060m,
            null,
            "",
            "Part",
            41),
        new(
            "2025-10-29",
            "SUSHOU PROFESSION ELEVATOR CO., LTD.",
            "Note: 50% Downpayment",
            "",
            null,
            null,
            4060m,
            null,
            "",
            "Note",
            42),
        new(
            "2025-12-09",
            "SUSHOU PROFESSION ELEVATOR CO., LTD.",
            "Control Cabinet SMR with PG Card & operator",
            "",
            1m,
            4060m,
            4060m,
            null,
            "",
            "Part",
            43),
        new(
            "2025-12-09",
            "SUSHOU PROFESSION ELEVATOR CO., LTD.",
            "Note: 50% Fullpayment",
            "",
            null,
            null,
            4060m,
            null,
            "",
            "Note",
            44),
    };
}
